### ISSUE TITLE
No Metrics Add

### ISSUE THREAD

**Issue by kvchoi** [niebes/retrofit-plugins#351]
I try out your code in my project, finally no metrics add to the  "Metrics.globalRegistry".
Debug into it , found this code skip creating a adapter for my returnType:
-----------------
@GET("/mobile")
PhoneHomeInfo mobile(@Header("Authorization") String authorization, @Query("mobile") String mobile);
-----------------
why must check the returnType in Call in "RetrofitMetricsFactory.kt" line 25 ? Can i skip that code ? 

if (getRawType(returnType) != Call::class.java) {
    return null
}

**Comment by niebes** [comment]
The Call contains information to process e.g. the retry.
You might want to keep this wrapper in your code and access the resulting body instead.
